spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/subwaydb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  sql:
    init:
      mode: always
